use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use liora_packager::{
    FontVariant, KnownApp, PackageFormat, PackageManifest, Platform, cargo_packager_formats,
    collect_package_artifacts, generated_config_path_for, generated_rpm_config_path_for,
    package_out_dir_for, release_binaries_dir, render_cargo_packager_config_for,
    render_generate_rpm_config_for, supplemental_formats, validate_packaging_layout,
};

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("package") => package(args.collect()),
        Some("help") | Some("--help") | Some("-h") | None => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!("unknown xtask command '{other}'")),
    }
}

fn package(args: Vec<String>) -> Result<(), String> {
    let command = PackageCommand::parse(args)?;
    match command.action {
        PackageAction::Validate => validate(),
        PackageAction::ReleaseReadiness => release_readiness(),
        PackageAction::Build => build(command.apps, command.font_variant),
        PackageAction::Smoke => smoke(command.apps, command.format, command.font_variant),
        PackageAction::InstallSmoke => install_smoke(
            command.apps,
            command.format,
            command.dry_run,
            command.execute_install,
            command.font_variant,
        ),
        PackageAction::Package | PackageAction::Ci => package_formats(command),
    }
}

fn validate() -> Result<(), String> {
    let root = workspace_root()?;
    let report = validate_packaging_layout(&root);
    if report.is_ok() {
        println!("packaging layout OK");
        return Ok(());
    }

    for error in report.errors {
        eprintln!("- {error}");
    }
    Err("packaging layout validation failed".into())
}

fn release_readiness() -> Result<(), String> {
    let root = workspace_root()?;
    let mut report = ReleaseReadinessReport::default();

    match validate() {
        Ok(()) => report.pass(
            "packaging layout",
            "all required packaging resources are present",
        ),
        Err(error) => report.fail("packaging layout", error),
    }

    check_license_policy(&root, &mut report);
    check_release_tag_policy(&mut report);
    check_signing_policy(&mut report);
    check_release_workflow(&root, &mut report);
    check_sdk_release_workflow(&root, &mut report);

    write_release_readiness_report(&root, &report)?;
    report.print();

    if report.has_failures() {
        Err("release readiness gate failed".into())
    } else {
        println!("release readiness OK");
        Ok(())
    }
}

#[derive(Debug, Default)]
struct ReleaseReadinessReport {
    items: Vec<ReleaseReadinessItem>,
}

#[derive(Debug)]
struct ReleaseReadinessItem {
    name: String,
    status: ReleaseReadinessStatus,
    detail: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ReleaseReadinessStatus {
    Pass,
    Warn,
    Fail,
}

impl ReleaseReadinessStatus {
    fn label(self) -> &'static str {
        match self {
            Self::Pass => "PASS",
            Self::Warn => "WARN",
            Self::Fail => "FAIL",
        }
    }

    fn markdown_icon(self) -> &'static str {
        match self {
            Self::Pass => "✅",
            Self::Warn => "⚠️",
            Self::Fail => "❌",
        }
    }
}

impl ReleaseReadinessReport {
    fn pass(&mut self, name: impl Into<String>, detail: impl Into<String>) {
        self.push(name, ReleaseReadinessStatus::Pass, detail);
    }

    fn warn(&mut self, name: impl Into<String>, detail: impl Into<String>) {
        self.push(name, ReleaseReadinessStatus::Warn, detail);
    }

    fn fail(&mut self, name: impl Into<String>, detail: impl Into<String>) {
        self.push(name, ReleaseReadinessStatus::Fail, detail);
    }

    fn push(
        &mut self,
        name: impl Into<String>,
        status: ReleaseReadinessStatus,
        detail: impl Into<String>,
    ) {
        self.items.push(ReleaseReadinessItem {
            name: name.into(),
            status,
            detail: detail.into(),
        });
    }

    fn has_failures(&self) -> bool {
        self.items
            .iter()
            .any(|item| item.status == ReleaseReadinessStatus::Fail)
    }

    fn print(&self) {
        for item in &self.items {
            println!(
                "release-readiness [{}] {}: {}",
                item.status.label(),
                item.name,
                item.detail
            );
        }
    }

    fn to_markdown(&self) -> String {
        let mut text = String::from("# Liora release readiness report\n\n");
        text.push_str(
            "This report is generated by `cargo run -p xtask -- package release-readiness`.\n\n",
        );
        text.push_str("| Status | Gate | Detail |\n");
        text.push_str("| --- | --- | --- |\n");
        for item in &self.items {
            text.push_str("| ");
            text.push_str(item.status.markdown_icon());
            text.push(' ');
            text.push_str(item.status.label());
            text.push_str(" | ");
            text.push_str(&escape_markdown_table_cell(&item.name));
            text.push_str(" | ");
            text.push_str(&escape_markdown_table_cell(&item.detail));
            text.push_str(" |\n");
        }
        text.push_str("\nAdvisory policy items are informational. Failures block publishing.\n");
        text
    }
}

fn check_license_policy(root: &Path, report: &mut ReleaseReadinessReport) {
    let license_path = root.join("LICENSE.md");
    match fs::read_to_string(&license_path) {
        Ok(text) if text.contains("LicenseRef-Liora") => report.pass(
            "license policy",
            "LICENSE.md declares the repository's current LicenseRef-Liora proprietary policy",
        ),
        Ok(_) => report.fail(
            "license policy",
            "LICENSE.md exists but does not declare the LicenseRef-Liora package policy",
        ),
        Err(_) => report.fail(
            "license policy",
            "missing LICENSE.md; choose OSS license metadata or document LicenseRef-Liora proprietary policy before release",
        ),
    }
}

fn check_release_tag_policy(report: &mut ReleaseReadinessReport) {
    let version = app_version();
    let base_version = env!("CARGO_PKG_VERSION");
    if let Ok(ref_name) = env::var("GITHUB_REF_NAME") {
        if let Some(tag_version) = ref_name.strip_prefix('v') {
            if tag_version == base_version && tag_version == version {
                report.pass(
                    "release tag version",
                    format!("tag {ref_name} matches package version {base_version}"),
                );
            } else {
                report.fail(
                    "release tag version",
                    format!(
                        "tag {ref_name} must match crates/liora-packager version {base_version} and LIORA_PACKAGE_VERSION {version}"
                    ),
                );
            }
            return;
        }
    }

    if version.contains("-preview.") {
        report.pass(
            "release tag version",
            format!("preview package version {version} is allowed outside v* releases"),
        );
    } else {
        report.pass(
            "release tag version",
            format!(
                "local or branch validation is not a v* release tag; package version is {version}"
            ),
        );
    }
}

fn check_signing_policy(report: &mut ReleaseReadinessReport) {
    let require_signing = env_truthy("LIORA_REQUIRE_SIGNING");
    let allow_unsigned_release = env_truthy("LIORA_ALLOW_UNSIGNED_RELEASE");
    let platform = Platform::current();
    let missing = signing_env_missing(platform);
    if missing.is_empty() {
        report.pass(
            "signing/notarization policy",
            format!("{} signing inputs are configured", platform.as_str()),
        );
    } else if require_signing {
        report.fail(
            "signing/notarization policy",
            format!(
                "LIORA_REQUIRE_SIGNING=true but missing {}",
                missing.join(", ")
            ),
        );
    } else if allow_unsigned_release {
        report.pass(
            "signing/notarization policy",
            format!(
                "unsigned build explicitly allowed by LIORA_ALLOW_UNSIGNED_RELEASE=true; provide {} and set LIORA_REQUIRE_SIGNING=true when signed release enforcement is required",
                missing.join(", ")
            ),
        );
    } else {
        report.warn(
            "signing/notarization policy",
            format!(
                "unsigned build allowed only when LIORA_ALLOW_UNSIGNED_RELEASE=true; otherwise provide {} or set LIORA_REQUIRE_SIGNING=true to fail closed",
                missing.join(", ")
            ),
        );
    }
}

fn signing_env_missing(platform: Platform) -> Vec<&'static str> {
    let required = match platform {
        Platform::Linux => &[][..],
        Platform::Macos => &[
            "LIORA_MACOS_CODESIGN_IDENTITY",
            "LIORA_MACOS_NOTARY_APPLE_ID",
            "LIORA_MACOS_NOTARY_TEAM_ID",
            "LIORA_MACOS_NOTARY_PASSWORD",
        ][..],
        Platform::Windows => &[
            "LIORA_WINDOWS_SIGNTOOL_CERT_PATH",
            "LIORA_WINDOWS_SIGNTOOL_CERT_PASSWORD",
            "LIORA_WINDOWS_TIMESTAMP_URL",
        ][..],
    };

    required
        .iter()
        .copied()
        .filter(|key| {
            env::var(key)
                .map(|value| value.trim().is_empty())
                .unwrap_or(true)
        })
        .collect()
}

fn env_truthy(key: &str) -> bool {
    env::var(key)
        .map(|value| {
            matches!(
                value.to_ascii_lowercase().as_str(),
                "1" | "true" | "yes" | "on"
            )
        })
        .unwrap_or(false)
}

fn check_release_workflow(root: &Path, report: &mut ReleaseReadinessReport) {
    let workflow_path = root.join(".github/workflows/package.yml");
    match fs::read_to_string(&workflow_path) {
        Ok(text)
            if text.contains("release-readiness")
                && text.contains("gh release create")
                && text.contains("liora-release-gallery-packages-*")
                && text.contains("liora-release-binaries-*") =>
        {
            report.pass(
                "release workflow",
                "package.yml contains release readiness, Gallery package artifacts, raw binary artifacts, grouped release notes, and GitHub Release upload steps",
            );
        }
        Ok(_) => report.fail(
            "release workflow",
            "package.yml is missing release-readiness, Gallery package artifacts, raw binary artifacts, or GitHub Release publishing steps",
        ),
        Err(_) => report.fail("release workflow", "missing .github/workflows/package.yml"),
    }
}

fn check_sdk_release_workflow(root: &Path, report: &mut ReleaseReadinessReport) {
    let workflow_path = root.join(".github/workflows/release-sdk.yml");
    match fs::read_to_string(&workflow_path) {
        Ok(text)
            if text.contains("CRATES_IO_TOKEN")
                && text.contains("cargo package -p")
                && text.contains("cargo publish -p")
                && !text.contains(concat!("cargo publish -p \"$crate\" ", "--", "token"))
                && text.contains("liora-theme liora-core liora-icons liora-icons-lucide liora-icons-antd liora-icons-ionic liora-icons-tabler liora-icons-carbon liora-icons-material liora-components liora-tray liora-packager liora") =>
        {
            report.pass(
                "SDK release workflow",
                "release-sdk.yml verifies and publishes SDK crates, including bundled icon libraries, liora, and liora-packager, with CARGO_REGISTRY_TOKEN authentication in dependency order",
            );
        }
        Ok(_) => report.fail(
            "SDK release workflow",
            "release-sdk.yml is missing SDK package verification, publish commands, environment-token wiring, liora/liora-packager crates, dependency order, or deprecated token-argument guard",
        ),
        Err(_) => report.fail("SDK release workflow", "missing .github/workflows/release-sdk.yml"),
    }
}

fn write_release_readiness_report(
    root: &Path,
    report: &ReleaseReadinessReport,
) -> Result<(), String> {
    let package_dir = root.join("target/packages");
    fs::create_dir_all(&package_dir)
        .map_err(|error| format!("failed to create {}: {error}", package_dir.display()))?;
    let path = package_dir.join("release-readiness.md");
    fs::write(&path, report.to_markdown())
        .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    println!("release readiness report written: {}", path.display());
    Ok(())
}

fn escape_markdown_table_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

fn smoke(
    apps: Vec<KnownApp>,
    format: PackageFormat,
    font_variant: FontVariant,
) -> Result<(), String> {
    let root = workspace_root()?;
    let platform = Platform::current();
    let formats: Vec<_> = if format == PackageFormat::PlatformDefaults {
        PackageFormat::defaults_for(platform).to_vec()
    } else {
        vec![format]
    };

    let mut checked = 0usize;
    for app in apps {
        let metadata = app.metadata();
        let out_dir = package_out_dir_for(&root, &metadata, platform, font_variant);
        let artifacts = collect_package_artifacts(
            &metadata.package,
            &app_version(),
            platform,
            &target_triple(),
            git_short_sha(&root).as_deref(),
            &out_dir,
            &formats,
        )
        .map_err(|error| {
            format!(
                "failed to inspect package artifacts from {}: {error}",
                out_dir.display()
            )
        })?;

        if artifacts.is_empty() {
            return Err(format!(
                "no package artifacts found for smoke: app={} output={} formats={}",
                metadata.package,
                out_dir.display(),
                formats
                    .iter()
                    .map(|format| format.as_str())
                    .collect::<Vec<_>>()
                    .join(",")
            ));
        }

        for artifact in artifacts {
            smoke_artifact(&root, &metadata, platform, artifact.format, &artifact.path)?;
            checked += 1;
        }
    }

    println!("package smoke OK: checked {checked} artifact(s)");
    Ok(())
}

fn install_smoke(
    apps: Vec<KnownApp>,
    format: PackageFormat,
    dry_run: bool,
    execute_install: bool,
    font_variant: FontVariant,
) -> Result<(), String> {
    let root = workspace_root()?;
    let platform = Platform::current();
    let formats: Vec<_> = if format == PackageFormat::PlatformDefaults {
        PackageFormat::defaults_for(platform).to_vec()
    } else {
        vec![format]
    };

    let mut plans = Vec::new();
    let mut checked = 0usize;
    for app in apps {
        let metadata = app.metadata();
        let out_dir = package_out_dir_for(&root, &metadata, platform, font_variant);
        if dry_run {
            for format in &formats {
                let path = expected_artifact_path(
                    &out_dir,
                    &metadata.package,
                    platform,
                    *format,
                    font_variant,
                );
                let plan = install_smoke_plan(&metadata, platform, *format, &path);
                println!("{plan}");
                plans.push(plan);
                checked += 1;
            }
            continue;
        }

        let artifacts = collect_package_artifacts(
            &metadata.package,
            &app_version(),
            platform,
            &target_triple(),
            git_short_sha(&root).as_deref(),
            &out_dir,
            &formats,
        )
        .map_err(|error| {
            format!(
                "failed to inspect package artifacts from {}: {error}",
                out_dir.display()
            )
        })?;

        if artifacts.is_empty() {
            return Err(format!(
                "no package artifacts found for install-smoke: app={} output={} formats={}",
                metadata.package,
                out_dir.display(),
                formats
                    .iter()
                    .map(|format| format.as_str())
                    .collect::<Vec<_>>()
                    .join(",")
            ));
        }

        for artifact in artifacts {
            smoke_artifact(&root, &metadata, platform, artifact.format, &artifact.path)?;
            let plan = install_smoke_plan(&metadata, platform, artifact.format, &artifact.path);
            println!("{plan}");
            if execute_install {
                execute_install_smoke(&root, &metadata, platform, artifact.format, &artifact.path)?;
            }
            plans.push(plan);
            checked += 1;
        }
    }

    write_install_smoke_plan(&root, &plans, execute_install)?;
    println!(
        "install-smoke {} OK: checked {checked} artifact(s)",
        if execute_install {
            "execute"
        } else if dry_run {
            "dry-run plan"
        } else {
            "plan"
        }
    );
    Ok(())
}

fn expected_artifact_path(
    out_dir: &Path,
    package: &str,
    platform: Platform,
    format: PackageFormat,
    font_variant: FontVariant,
) -> PathBuf {
    match (platform, format) {
        (_, PackageFormat::TarGz) => portable_tar_gz_path(
            out_dir,
            package,
            &app_version(),
            platform,
            &target_triple(),
            font_variant,
        ),
        (Platform::Linux, PackageFormat::Deb) => {
            out_dir.join(format!("{package}_{}_amd64.deb", app_version()))
        }
        (Platform::Linux, PackageFormat::Rpm) => {
            out_dir.join(format!("{package}-{}.x86_64.rpm", app_version()))
        }
        (Platform::Linux, PackageFormat::AppImage) => {
            out_dir.join(format!("{package}-{}.AppImage", app_version()))
        }
        (Platform::Macos, PackageFormat::App) => out_dir.join(format!("{package}.app")),
        (Platform::Macos, PackageFormat::Dmg) => {
            out_dir.join(format!("{package}_{}.dmg", app_version()))
        }
        (Platform::Windows, PackageFormat::Nsis) => {
            out_dir.join(format!("{package}_{}_setup.exe", app_version()))
        }
        (Platform::Windows, PackageFormat::Msi) => {
            out_dir.join(format!("{package}_{}.msi", app_version()))
        }
        (_, other) => out_dir.join(format!("{package}-{}.{}", app_version(), other.as_str())),
    }
}

fn install_smoke_plan(
    app: &liora_packager::AppMetadata,
    platform: Platform,
    format: PackageFormat,
    path: &Path,
) -> String {
    let path = path.display();
    match (platform, format) {
        (Platform::Linux, PackageFormat::Deb) => format!(
            "install-smoke plan: app={} format=deb\n  install: sudo dpkg -i {path} || sudo apt-get -f install -y\n  smoke: timeout 15s {} || true  # GUI app may stay open until timeout\n  uninstall: sudo apt-get remove -y {}",
            app.package, app.binary, app.package
        ),
        (Platform::Linux, PackageFormat::Rpm) => format!(
            "install-smoke plan: app={} format=rpm\n  install: sudo rpm -Uvh {path}\n  smoke: timeout 15s {} || true  # GUI app may stay open until timeout\n  uninstall: sudo rpm -e {}",
            app.package, app.binary, app.package
        ),
        (Platform::Linux, PackageFormat::AppImage) => format!(
            "install-smoke plan: app={} format=appimage\n  install: chmod +x {path}\n  smoke: timeout 15s {path} || true  # GUI app may stay open until timeout\n  uninstall: rm -f <copied-appimage-if-installed>",
            app.package
        ),
        (_, PackageFormat::TarGz) => format!(
            "install-smoke plan: app={} format=tar.gz\n  install: mkdir -p target/install-smoke && tar -xzf {path} -C target/install-smoke\n  smoke: verify launcher, bin/{}, icons and README exist\n  uninstall: rm -rf target/install-smoke/{}-*",
            app.package, app.binary, app.package
        ),
        (Platform::Macos, PackageFormat::App) => format!(
            "install-smoke plan: app={} format=app\n  install: cp -R {path} /tmp/liora-install-smoke/\n  smoke: open -W -n /tmp/liora-install-smoke/*.app --args --smoke if supported\n  uninstall: rm -rf /tmp/liora-install-smoke",
            app.package
        ),
        (Platform::Macos, PackageFormat::Dmg) => format!(
            "install-smoke plan: app={} format=dmg\n  install: hdiutil attach {path}; copy .app to /tmp/liora-install-smoke\n  smoke: open copied .app if runner policy allows\n  uninstall: hdiutil detach <mount>; rm -rf /tmp/liora-install-smoke",
            app.package
        ),
        (Platform::Windows, PackageFormat::Nsis) => format!(
            "install-smoke plan: app={} format=nsis\n  install: {path} /S /D=%TEMP%\\LioraInstallSmoke\\{}\n  smoke: run installed {}.exe with timeout if runner policy allows\n  uninstall: invoke generated uninstaller silently, then remove temp directory",
            app.package, app.binary, app.binary
        ),
        (Platform::Windows, PackageFormat::Msi) => format!(
            "install-smoke plan: app={} format=msi\n  install: msiexec /i {path} /qn TARGETDIR=%TEMP%\\LioraInstallSmoke\\{}\n  smoke: run installed {}.exe with timeout if runner policy allows\n  uninstall: msiexec /x {path} /qn",
            app.package, app.binary, app.binary
        ),
        (_, other) => format!(
            "install-smoke plan: app={} format={}\n  artifact: {path}\n  install/uninstall smoke is platform-specific and currently plan-only",
            app.package,
            other.as_str()
        ),
    }
}

fn execute_install_smoke(
    root: &Path,
    app: &liora_packager::AppMetadata,
    platform: Platform,
    format: PackageFormat,
    path: &Path,
) -> Result<(), String> {
    match format {
        PackageFormat::TarGz => execute_portable_install_smoke(root, app, platform, path),
        _ => Err(format!(
            "refusing to execute install-smoke for format={} without a dedicated safe executor; rerun without --execute-install to generate the plan",
            format.as_str()
        )),
    }
}

fn execute_portable_install_smoke(
    root: &Path,
    app: &liora_packager::AppMetadata,
    platform: Platform,
    path: &Path,
) -> Result<(), String> {
    smoke_portable_tar_gz(app, platform, path)?;
    let install_root = root.join("target").join("install-smoke").join(&app.package);
    if install_root.exists() {
        fs::remove_dir_all(&install_root)
            .map_err(|error| format!("failed to reset {}: {error}", install_root.display()))?;
    }
    fs::create_dir_all(&install_root)
        .map_err(|error| format!("failed to create {}: {error}", install_root.display()))?;

    let status = Command::new("tar")
        .arg("-xzf")
        .arg(path)
        .arg("-C")
        .arg(&install_root)
        .status()
        .map_err(|error| format!("failed to spawn tar for install-smoke: {error}"))?;
    if !status.success() {
        return Err(format!(
            "portable install-smoke extraction failed: {}",
            path.display()
        ));
    }

    let mut found_launcher = false;
    for entry in fs::read_dir(&install_root)
        .map_err(|error| format!("failed to list {}: {error}", install_root.display()))?
    {
        let entry =
            entry.map_err(|error| format!("failed to read install-smoke entry: {error}"))?;
        let candidate = entry.path().join(&app.binary);
        let bin_candidate = entry.path().join("bin").join(&app.binary);
        if candidate.is_file() && bin_candidate.is_file() {
            found_launcher = true;
            break;
        }
    }
    if !found_launcher {
        return Err(format!(
            "portable install-smoke did not find launcher and bin binary under {}",
            install_root.display()
        ));
    }

    fs::remove_dir_all(&install_root).map_err(|error| {
        format!(
            "failed to uninstall portable smoke dir {}: {error}",
            install_root.display()
        )
    })?;
    println!(
        "install-smoke execute OK: app={} format=tar.gz install-root={}",
        app.package,
        install_root.display()
    );
    Ok(())
}

fn write_install_smoke_plan(
    root: &Path,
    plans: &[String],
    execute_install: bool,
) -> Result<(), String> {
    let package_dir = root.join("target").join("packages");
    fs::create_dir_all(&package_dir)
        .map_err(|error| format!("failed to create {}: {error}", package_dir.display()))?;
    let path = package_dir.join("install-smoke-plan.md");
    let mut text = String::from("# Liora package install/uninstall smoke plan\n\n");
    text.push_str(if execute_install {
        "Mode: execute selected safe install smoke paths.\n\n"
    } else {
        "Mode: plan-only. No system package installation was performed.\n\n"
    });
    for plan in plans {
        text.push_str("```text\n");
        text.push_str(plan);
        text.push_str("\n```\n\n");
    }
    fs::write(&path, text)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    println!("install-smoke plan written: {}", path.display());
    Ok(())
}

fn smoke_artifact(
    _root: &Path,
    app: &liora_packager::AppMetadata,
    platform: Platform,
    format: PackageFormat,
    path: &Path,
) -> Result<(), String> {
    match format {
        PackageFormat::TarGz => smoke_portable_tar_gz(app, platform, path),
        PackageFormat::Deb => require_magic(path, b"!<arch>\n", "deb ar archive"),
        PackageFormat::Rpm => require_magic(path, &[0xed, 0xab, 0xee, 0xdb], "rpm lead"),
        PackageFormat::Nsis => require_magic(path, b"MZ", "Windows executable"),
        PackageFormat::Msi => require_magic(
            path,
            &[0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1],
            "MSI compound document",
        ),
        PackageFormat::AppImage | PackageFormat::Dmg | PackageFormat::App => {
            let len = fs::metadata(path)
                .map_err(|error| format!("failed to stat {}: {error}", path.display()))?
                .len();
            if len == 0 {
                Err(format!("package artifact is empty: {}", path.display()))
            } else {
                println!(
                    "package smoke OK: app={} format={} path={} bytes={}",
                    app.package,
                    format.as_str(),
                    path.display(),
                    len
                );
                Ok(())
            }
        }
        PackageFormat::PlatformDefaults => Ok(()),
    }
}

fn smoke_portable_tar_gz(
    app: &liora_packager::AppMetadata,
    platform: Platform,
    path: &Path,
) -> Result<(), String> {
    let output = Command::new("tar")
        .arg("-tzf")
        .arg(path)
        .output()
        .map_err(|error| format!("failed to spawn tar for {}: {error}", path.display()))?;
    if !output.status.success() {
        return Err(format!(
            "portable tar.gz listing failed for {}: {}",
            path.display(),
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let entries = String::from_utf8_lossy(&output.stdout);
    let top = entries
        .lines()
        .find_map(|entry| entry.split('/').next())
        .filter(|entry| !entry.is_empty())
        .ok_or_else(|| format!("portable tar.gz is empty: {}", path.display()))?;

    let required = [
        format!("{top}/bin/{}", app.binary),
        format!("{top}/icons/{}.png", app.icon_stem),
        format!("{top}/icons/{}.svg", app.icon_stem),
        format!("{top}/{}", app.binary),
        format!("{top}/README.md"),
    ];
    for required_entry in required {
        if !tar_listing_contains(&entries, &required_entry) {
            return Err(format!(
                "portable tar.gz missing required entry `{required_entry}` in {}",
                path.display()
            ));
        }
    }

    if platform == Platform::Linux {
        for required_entry in [
            format!("{top}/share/applications/{}.desktop", app.binary),
            format!("{top}/share/metainfo/{}.metainfo.xml", app.binary),
            format!("{top}/share/icons/hicolor/16x16/apps/{}.png", app.binary),
            format!("{top}/share/icons/hicolor/512x512/apps/{}.png", app.binary),
            format!("{top}/install-desktop.sh"),
            format!("{top}/uninstall-desktop.sh"),
        ] {
            if !tar_listing_contains(&entries, &required_entry) {
                return Err(format!(
                    "portable tar.gz missing Linux metadata entry `{required_entry}` in {}",
                    path.display()
                ));
            }
        }
    }

    println!(
        "package smoke OK: app={} format=tar.gz path={}",
        app.package,
        path.display()
    );
    Ok(())
}

fn tar_listing_contains(entries: &str, required_entry: &str) -> bool {
    entries
        .lines()
        .any(|entry| entry.trim_end_matches('/') == required_entry)
}

fn require_magic(path: &Path, magic: &[u8], label: &str) -> Result<(), String> {
    let bytes =
        fs::read(path).map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    if bytes.starts_with(magic) {
        println!(
            "package smoke OK: {} path={} bytes={}",
            label,
            path.display(),
            bytes.len()
        );
        Ok(())
    } else {
        Err(format!(
            "package artifact has unexpected header for {label}: {}",
            path.display()
        ))
    }
}

fn build(apps: Vec<KnownApp>, font_variant: FontVariant) -> Result<(), String> {
    for app in apps {
        let mut args = vec!["build", "--release", "-p", app.package()];
        if font_variant == FontVariant::WithFonts {
            args.extend(["--features", "embedded-fonts"]);
        }
        let status = Command::new("cargo")
            .args(args)
            .status()
            .map_err(|error| format!("failed to spawn cargo build: {error}"))?;
        if !status.success() {
            return Err(format!("cargo build failed for {}", app.package()));
        }
    }
    Ok(())
}

fn package_formats(command: PackageCommand) -> Result<(), String> {
    validate()?;
    if !command.skip_build {
        build(command.apps.clone(), command.font_variant)?;
    }

    let root = workspace_root()?;
    let platform = Platform::current();
    let formats: Vec<_> = if command.format == PackageFormat::PlatformDefaults {
        PackageFormat::defaults_for(platform).to_vec()
    } else {
        vec![command.format]
    };

    let mut manifest = PackageManifest::default();

    for app in command.apps {
        let metadata = app.metadata();
        let cargo_formats = cargo_packager_formats(&formats);
        let supplemental = supplemental_formats(&formats);
        let out_dir = package_out_dir_for(&root, &metadata, platform, command.font_variant);
        let binaries_dir = release_binaries_dir(&root);
        let target_triple = target_triple();
        let git_sha = git_short_sha(&root);

        if !cargo_formats.is_empty() {
            let config_path = generated_config_path_for(&root, &metadata, command.font_variant);
            let config_text = render_cargo_packager_config_for(
                &root,
                &metadata,
                &cargo_formats,
                &out_dir,
                &binaries_dir,
                command.font_variant,
            );
            if let Some(parent) = config_path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
            }
            fs::write(&config_path, config_text)
                .map_err(|error| format!("failed to write {}: {error}", config_path.display()))?;

            let args = cargo_packager_args(&config_path, &out_dir, &binaries_dir, &cargo_formats);
            println!(
                "cargo-packager config: app={} path={}",
                metadata.package,
                config_path.display()
            );
            if command.dry_run {
                println!("dry-run: cargo {}", args.join(" "));
            } else {
                run_cargo_packager(&args)?;
            }
        }

        for format in supplemental {
            if format == PackageFormat::TarGz {
                let archive_path = portable_tar_gz_path(
                    &out_dir,
                    &metadata.package,
                    &app_version(),
                    platform,
                    &target_triple,
                    command.font_variant,
                );
                println!(
                    "portable tar.gz package: app={} path={}",
                    metadata.package,
                    archive_path.display()
                );
                if command.dry_run {
                    println!(
                        "dry-run: stage release binary, icons, metadata, README and launcher; tar -czf {} -C <staging-parent> <staging-dir>",
                        archive_path.display()
                    );
                } else {
                    build_portable_tar_gz(
                        &root,
                        &metadata,
                        platform,
                        &target_triple,
                        git_sha.as_deref(),
                        &out_dir,
                        &archive_path,
                        command.font_variant,
                    )?;
                }
            } else if format == PackageFormat::Rpm && platform == Platform::Linux {
                let config_path =
                    generated_rpm_config_path_for(&root, &metadata, command.font_variant);
                if let Some(parent) = config_path.parent() {
                    fs::create_dir_all(parent).map_err(|error| {
                        format!("failed to create {}: {error}", parent.display())
                    })?;
                }
                fs::write(
                    &config_path,
                    render_generate_rpm_config_for(&root, &metadata, command.font_variant),
                )
                .map_err(|error| format!("failed to write {}: {error}", config_path.display()))?;
                let args = generate_rpm_args(&root, app, &config_path, &out_dir);
                println!(
                    "generate-rpm config: app={} path={}",
                    metadata.package,
                    config_path.display()
                );
                if command.dry_run {
                    println!("dry-run: cargo {}", args.join(" "));
                } else {
                    run_generate_rpm(&args)?;
                }
            } else {
                println!(
                    "supplemental package pending: app={} platform={} format={} output={}",
                    metadata.package,
                    platform.as_str(),
                    format.as_str(),
                    out_dir.display()
                );
            }
        }

        if !command.dry_run {
            let artifacts = collect_package_artifacts(
                &metadata.package,
                &app_version(),
                platform,
                &target_triple,
                git_sha.as_deref(),
                &out_dir,
                &formats,
            )
            .map_err(|error| {
                format!(
                    "failed to collect package artifacts from {}: {error}",
                    out_dir.display()
                )
            })?;
            if artifacts.is_empty() {
                println!(
                    "no package artifacts discovered yet: app={} output={}",
                    metadata.package,
                    out_dir.display()
                );
            } else {
                println!(
                    "discovered {} package artifact(s): app={} output={}",
                    artifacts.len(),
                    metadata.package,
                    out_dir.display()
                );
            }
            manifest.extend(artifacts);
        }
    }

    if !command.dry_run {
        write_manifest_outputs(&root, &manifest)?;
    }

    Ok(())
}

fn portable_tar_gz_path(
    out_dir: &Path,
    package: &str,
    version: &str,
    platform: Platform,
    target_triple: &str,
    font_variant: FontVariant,
) -> PathBuf {
    out_dir.join(format!(
        "{package}-{version}-{}-{target_triple}-{}.tar.gz",
        platform.as_str(),
        font_variant.as_str()
    ))
}

fn build_portable_tar_gz(
    root: &Path,
    app: &liora_packager::AppMetadata,
    platform: Platform,
    target_triple: &str,
    git_sha: Option<&str>,
    out_dir: &Path,
    archive_path: &Path,
    font_variant: FontVariant,
) -> Result<(), String> {
    let binary_path = root.join("target/release").join(&app.binary);
    if !binary_path.is_file() {
        return Err(format!(
            "release binary not found for portable tar.gz: {}; run `cargo run -p xtask -- package build --app {}` first or omit --skip-build",
            binary_path.display(),
            app.app.key()
        ));
    }

    fs::create_dir_all(out_dir)
        .map_err(|error| format!("failed to create {}: {error}", out_dir.display()))?;

    let stage_name = format!(
        "{}-{}-{}-{target_triple}-{}",
        app.package,
        app_version(),
        platform.as_str(),
        font_variant.as_str()
    );
    let stage_root = out_dir.join("portable-staging").join(&stage_name);
    if stage_root.exists() {
        fs::remove_dir_all(&stage_root)
            .map_err(|error| format!("failed to reset {}: {error}", stage_root.display()))?;
    }

    fs::create_dir_all(stage_root.join("bin"))
        .map_err(|error| format!("failed to create staging bin directory: {error}"))?;
    fs::create_dir_all(stage_root.join("icons"))
        .map_err(|error| format!("failed to create staging icons directory: {error}"))?;
    fs::create_dir_all(stage_root.join("share/icons/hicolor"))
        .map_err(|error| format!("failed to create staging hicolor directory: {error}"))?;
    fs::create_dir_all(stage_root.join("share/applications"))
        .map_err(|error| format!("failed to create staging desktop directory: {error}"))?;
    fs::create_dir_all(stage_root.join("share/metainfo"))
        .map_err(|error| format!("failed to create staging metainfo directory: {error}"))?;

    copy_file(&binary_path, &stage_root.join("bin").join(&app.binary))?;
    copy_file(
        &root
            .join("packaging/icons")
            .join(format!("{}.png", app.icon_stem)),
        &stage_root
            .join("icons")
            .join(format!("{}.png", app.icon_stem)),
    )?;
    copy_file(
        &root
            .join("packaging/icons")
            .join(format!("{}.svg", app.icon_stem)),
        &stage_root
            .join("icons")
            .join(format!("{}.svg", app.icon_stem)),
    )?;
    for size in [16, 24, 32, 48, 64, 128, 256, 512] {
        copy_file(
            &app.hicolor_png_path(root, size),
            &stage_root
                .join("share/icons/hicolor")
                .join(format!("{size}x{size}"))
                .join("apps")
                .join(format!("{}.png", app.binary)),
        )?;
    }

    if font_variant.includes_fonts() {
        copy_dir_if_exists(
            &app.app_assets_fonts_path(root),
            &stage_root.join("assets/fonts"),
        )?;
    }

    if platform == Platform::Linux {
        copy_file(
            &app.linux_desktop_path(root),
            &stage_root
                .join("share/applications")
                .join(format!("{}.desktop", app.binary)),
        )?;
        copy_file(
            &app.linux_metainfo_path(root),
            &stage_root
                .join("share/metainfo")
                .join(format!("{}.metainfo.xml", app.binary)),
        )?;
        write_portable_linux_desktop_scripts(&stage_root, app)?;
    }

    write_portable_launcher(&stage_root.join(app.binary.as_str()), &app.binary)?;
    write_portable_readme(
        &stage_root.join("README.md"),
        app,
        platform,
        target_triple,
        git_sha,
    )?;

    if archive_path.exists() {
        fs::remove_file(archive_path)
            .map_err(|error| format!("failed to replace {}: {error}", archive_path.display()))?;
    }
    let parent = stage_root
        .parent()
        .ok_or_else(|| format!("staging path has no parent: {}", stage_root.display()))?;
    let status = Command::new("tar")
        .arg("-czf")
        .arg(archive_path)
        .arg("-C")
        .arg(parent)
        .arg(&stage_name)
        .status()
        .map_err(|error| format!("failed to spawn tar: {error}"))?;
    if !status.success() {
        return Err("portable tar.gz backend failed; ensure system `tar` is available".into());
    }
    println!("portable tar.gz written: {}", archive_path.display());
    Ok(())
}

fn copy_dir_if_exists(source: &Path, dest: &Path) -> Result<(), String> {
    if !source.exists() {
        return Ok(());
    }

    for entry in fs::read_dir(source)
        .map_err(|error| format!("failed to read {}: {error}", source.display()))?
    {
        let entry = entry.map_err(|error| {
            format!(
                "failed to read directory entry in {}: {error}",
                source.display()
            )
        })?;
        let source_path = entry.path();
        let dest_path = dest.join(entry.file_name());
        let file_type = entry
            .file_type()
            .map_err(|error| format!("failed to inspect {}: {error}", source_path.display()))?;
        if file_type.is_dir() {
            copy_dir_if_exists(&source_path, &dest_path)?;
        } else if file_type.is_file() {
            copy_file(&source_path, &dest_path)?;
        }
    }
    Ok(())
}

fn copy_file(source: &Path, dest: &Path) -> Result<(), String> {
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
    }
    fs::copy(source, dest).map_err(|error| {
        format!(
            "failed to copy {} to {}: {error}",
            source.display(),
            dest.display()
        )
    })?;
    Ok(())
}

fn write_portable_linux_desktop_scripts(
    stage_root: &Path,
    app: &liora_packager::AppMetadata,
) -> Result<(), String> {
    let install_script = format!(
        r#"#!/usr/bin/env sh
set -eu
DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
DATA_HOME="${{XDG_DATA_HOME:-$HOME/.local/share}}"
mkdir -p "$DATA_HOME/applications" "$DATA_HOME/icons/hicolor"
cp "$DIR/share/applications/{binary}.desktop" "$DATA_HOME/applications/{binary}.desktop"
for size in 16 24 32 48 64 128 256 512; do
  mkdir -p "$DATA_HOME/icons/hicolor/${{size}}x${{size}}/apps"
  cp "$DIR/share/icons/hicolor/${{size}}x${{size}}/apps/{binary}.png" "$DATA_HOME/icons/hicolor/${{size}}x${{size}}/apps/{binary}.png"
done
mkdir -p "$DATA_HOME/icons/hicolor/scalable/apps"
cp "$DIR/icons/{icon_stem}.svg" "$DATA_HOME/icons/hicolor/scalable/apps/{binary}.svg"
if command -v update-desktop-database >/dev/null 2>&1; then update-desktop-database "$DATA_HOME/applications" >/dev/null 2>&1 || true; fi
if command -v kbuildsycoca6 >/dev/null 2>&1; then kbuildsycoca6 --noincremental >/dev/null 2>&1 || true; fi
if command -v kbuildsycoca5 >/dev/null 2>&1; then kbuildsycoca5 --noincremental >/dev/null 2>&1 || true; fi
echo "Installed {name} desktop integration into $DATA_HOME"
"#,
        binary = app.binary,
        icon_stem = app.icon_stem,
        name = app.name
    );
    let uninstall_script = format!(
        r#"#!/usr/bin/env sh
set -eu
DATA_HOME="${{XDG_DATA_HOME:-$HOME/.local/share}}"
rm -f "$DATA_HOME/applications/{binary}.desktop"
for size in 16 24 32 48 64 128 256 512; do
  rm -f "$DATA_HOME/icons/hicolor/${{size}}x${{size}}/apps/{binary}.png"
done
rm -f "$DATA_HOME/icons/hicolor/scalable/apps/{binary}.svg"
if command -v update-desktop-database >/dev/null 2>&1; then update-desktop-database "$DATA_HOME/applications" >/dev/null 2>&1 || true; fi
if command -v kbuildsycoca6 >/dev/null 2>&1; then kbuildsycoca6 --noincremental >/dev/null 2>&1 || true; fi
if command -v kbuildsycoca5 >/dev/null 2>&1; then kbuildsycoca5 --noincremental >/dev/null 2>&1 || true; fi
echo "Removed {name} desktop integration from $DATA_HOME"
"#,
        binary = app.binary,
        name = app.name
    );
    write_executable_script(&stage_root.join("install-desktop.sh"), &install_script)?;
    write_executable_script(&stage_root.join("uninstall-desktop.sh"), &uninstall_script)
}

fn write_executable_script(path: &Path, script: &str) -> Result<(), String> {
    fs::write(path, script)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .map_err(|error| format!("failed to stat {}: {error}", path.display()))?
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions)
            .map_err(|error| format!("failed to chmod {}: {error}", path.display()))?;
    }
    Ok(())
}

fn write_portable_launcher(path: &Path, binary: &str) -> Result<(), String> {
    let script = format!(
        "#!/usr/bin/env sh\nset -eu\nDIR=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"\nexec \"$DIR/bin/{binary}\" \"$@\"\n"
    );
    fs::write(path, script)
        .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .map_err(|error| format!("failed to stat {}: {error}", path.display()))?
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions)
            .map_err(|error| format!("failed to chmod {}: {error}", path.display()))?;
    }
    Ok(())
}

fn write_portable_readme(
    path: &Path,
    app: &liora_packager::AppMetadata,
    platform: Platform,
    target_triple: &str,
    git_sha: Option<&str>,
) -> Result<(), String> {
    let git_line = git_sha
        .map(|sha| format!("- Git SHA: `{sha}`\n"))
        .unwrap_or_default();
    let text = format!(
        "# {name} portable archive\n\nThis archive contains a pure Rust + GPUI native Liora application. It does not bundle or require Tauri, WebView, HTML/CSS, or browser runtime architecture.\n\n## Metadata\n\n- Package: `{package}`\n- Version: `{version}`\n- Platform: `{platform}`\n- Target triple: `{target_triple}`\n{git_line}\n## Run\n\n```bash\n./{binary}\n# or\n./bin/{binary}\n```\n\nLinux desktop metadata is included under `share/` when the archive is built on Linux. Run `./install-desktop.sh` from the extracted archive to register the app in your desktop application menu, and `./uninstall-desktop.sh` to remove that registration.\n",
        name = app.name,
        package = app.package,
        version = app_version(),
        platform = platform.as_str(),
        binary = app.binary,
    );
    fs::write(path, text).map_err(|error| format!("failed to write {}: {error}", path.display()))
}

fn target_triple() -> String {
    env::var("CARGO_BUILD_TARGET")
        .or_else(|_| env::var("TARGET"))
        .ok()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| {
            rustc_host_triple()
                .unwrap_or_else(|| format!("{}-{}", env::consts::ARCH, env::consts::OS))
        })
}

fn rustc_host_triple() -> Option<String> {
    let output = Command::new("rustc").arg("-vV").output().ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .find_map(|line| line.strip_prefix("host: ").map(str::to_string))
}

fn git_short_sha(root: &Path) -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short=12", "HEAD"])
        .current_dir(root)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let sha = String::from_utf8_lossy(&output.stdout).trim().to_string();
    (!sha.is_empty()).then_some(sha)
}

fn write_manifest_outputs(
    root: &std::path::Path,
    manifest: &PackageManifest,
) -> Result<(), String> {
    let package_dir = root.join("target/packages");
    fs::create_dir_all(&package_dir)
        .map_err(|error| format!("failed to create {}: {error}", package_dir.display()))?;
    let manifest_path = package_dir.join("package-manifest.json");
    fs::write(&manifest_path, manifest.to_json_pretty())
        .map_err(|error| format!("failed to write {}: {error}", manifest_path.display()))?;
    let checksum_path = package_dir.join("checksums.txt");
    fs::write(&checksum_path, manifest.checksums_txt())
        .map_err(|error| format!("failed to write {}: {error}", checksum_path.display()))?;
    let release_notes_path = package_dir.join("release-notes.md");
    fs::write(&release_notes_path, manifest.release_notes_markdown())
        .map_err(|error| format!("failed to write {}: {error}", release_notes_path.display()))?;
    if manifest.is_empty() {
        println!(
            "package manifest written with no artifacts yet: {}",
            manifest_path.display()
        );
    } else {
        println!(
            "package manifest written: {} ({} artifact(s))",
            manifest_path.display(),
            manifest.artifacts.len()
        );
        println!("checksums written: {}", checksum_path.display());
        println!("release notes written: {}", release_notes_path.display());
    }
    Ok(())
}

fn app_version() -> String {
    env::var("LIORA_PACKAGE_VERSION").unwrap_or_else(|_| env!("CARGO_PKG_VERSION").to_string())
}

fn cargo_packager_args(
    config_path: &std::path::Path,
    out_dir: &std::path::Path,
    binaries_dir: &std::path::Path,
    formats: &[PackageFormat],
) -> Vec<String> {
    let format_arg = formats
        .iter()
        .filter_map(|format| format.cargo_packager_format())
        .collect::<Vec<_>>()
        .join(",");
    vec![
        "packager".into(),
        "--config".into(),
        config_path.display().to_string(),
        "--out-dir".into(),
        out_dir.display().to_string(),
        "--binaries-dir".into(),
        binaries_dir.display().to_string(),
        "--formats".into(),
        format_arg,
    ]
}

fn generate_rpm_args(
    root: &std::path::Path,
    app: KnownApp,
    config_path: &std::path::Path,
    out_dir: &std::path::Path,
) -> Vec<String> {
    let package_dir = root.join("apps").join(app.package());
    vec![
        "generate-rpm".into(),
        "--package".into(),
        package_dir.display().to_string(),
        "--output".into(),
        out_dir.display().to_string(),
        "--metadata-overwrite".into(),
        format!("{}#package.metadata.generate-rpm", config_path.display()),
        "--auto-req".into(),
        "builtin".into(),
    ]
}

fn run_generate_rpm(args: &[String]) -> Result<(), String> {
    let status = Command::new("cargo")
        .args(args)
        .status()
        .map_err(|error| format!("failed to spawn cargo generate-rpm: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(
            "cargo generate-rpm failed; install backend with `cargo install cargo-generate-rpm --locked` and ensure rpm build prerequisites are available"
                .into(),
        )
    }
}

fn run_cargo_packager(args: &[String]) -> Result<(), String> {
    let status = Command::new("cargo")
        .args(args)
        .status()
        .map_err(|error| format!("failed to spawn cargo packager: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(
            "cargo packager failed; install backend with `cargo install cargo-packager --locked` and ensure platform tools are available"
                .into(),
        )
    }
}

#[derive(Debug)]
struct PackageCommand {
    action: PackageAction,
    apps: Vec<KnownApp>,
    format: PackageFormat,
    dry_run: bool,
    skip_build: bool,
    execute_install: bool,
    font_variant: FontVariant,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PackageAction {
    Validate,
    ReleaseReadiness,
    Build,
    Smoke,
    InstallSmoke,
    Package,
    Ci,
}

impl PackageCommand {
    fn parse(args: Vec<String>) -> Result<Self, String> {
        let mut action = PackageAction::Package;
        let mut app: Option<KnownApp> = None;
        let mut all_apps = false;
        let mut format = PackageFormat::PlatformDefaults;
        let mut dry_run = false;
        let mut skip_build = false;
        let mut execute_install = false;
        let mut font_variant = FontVariant::WithoutFonts;
        let mut iter = args.into_iter();

        while let Some(arg) = iter.next() {
            match arg.as_str() {
                "validate" => action = PackageAction::Validate,
                "release-readiness" => action = PackageAction::ReleaseReadiness,
                "build" => action = PackageAction::Build,
                "smoke" => action = PackageAction::Smoke,
                "install-smoke" => action = PackageAction::InstallSmoke,
                "ci" => action = PackageAction::Ci,
                "--all-apps" => all_apps = true,
                "--dry-run" => dry_run = true,
                "--skip-build" => skip_build = true,
                "--execute-install" => execute_install = true,
                "--app" => {
                    let value = iter.next().ok_or("--app requires a value")?;
                    app = Some(value.parse()?);
                }
                "--format" => {
                    let value = iter.next().ok_or("--format requires a value")?;
                    format = value.parse()?;
                }
                "--font-variant" => {
                    let value = iter.next().ok_or("--font-variant requires a value")?;
                    font_variant = value.parse()?;
                }
                "--help" | "-h" => {
                    print_help();
                    std::process::exit(0);
                }
                other => return Err(format!("unknown package argument '{other}'")),
            }
        }

        let apps = if all_apps {
            liora_packager::known_apps().to_vec()
        } else {
            vec![app.unwrap_or(KnownApp::Gallery)]
        };

        Ok(Self {
            action,
            apps,
            format,
            dry_run,
            skip_build,
            execute_install,
            font_variant,
        })
    }
}

fn workspace_root() -> Result<PathBuf, String> {
    env::current_dir().map_err(|error| format!("failed to read current directory: {error}"))
}

fn print_help() {
    println!(
        "Liora xtask\n\n  cargo run -p xtask -- package validate\n  cargo run -p xtask -- package build --app gallery\n  cargo run -p xtask -- package --app docs --format appimage\n  cargo run -p xtask -- package --app docs --format deb --dry-run --skip-build\n  cargo run -p xtask -- package ci --all-apps --format platform-defaults\n  cargo run -p xtask -- package smoke --all-apps --format platform-defaults
  cargo run -p xtask -- package install-smoke --all-apps --format platform-defaults --dry-run\n\nOptions:\n  --app <gallery|docs>\n  --all-apps\n  --format <appimage|deb|rpm|tar.gz|app|dmg|nsis|msi|platform-defaults>\n  --dry-run      generate backend config and print cargo-packager invocation\n  --skip-build   reuse target/release binaries instead of building first
  --execute-install  execute only safe install-smoke paths (currently portable tar.gz)"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn target_triple_prefers_explicit_env() {
        // SAFETY: This unit test mutates process environment and does not spawn
        // threads. It restores the variables before returning.
        unsafe {
            env::set_var("CARGO_BUILD_TARGET", "aarch64-apple-darwin");
            env::remove_var("TARGET");
        }
        assert_eq!(target_triple(), "aarch64-apple-darwin");
        unsafe {
            env::remove_var("CARGO_BUILD_TARGET");
        }
    }

    #[test]
    fn portable_tar_gz_name_contains_package_version_platform_and_target() {
        let path = portable_tar_gz_path(
            Path::new("out"),
            "liora-gallery",
            "1.2.3-preview.4.abcdef0",
            Platform::Linux,
            "x86_64-unknown-linux-gnu",
            FontVariant::WithFonts,
        );
        assert_eq!(
            path,
            Path::new("out").join(
                "liora-gallery-1.2.3-preview.4.abcdef0-linux-x86_64-unknown-linux-gnu-with-fonts.tar.gz"
            )
        );
    }

    #[test]
    fn portable_tar_listing_checks_required_entries() {
        let entries = "liora-gallery/\nliora-gallery/bin/liora-gallery\nliora-gallery/assets/fonts/\nliora-gallery/README.md\n";
        assert!(tar_listing_contains(
            entries,
            "liora-gallery/bin/liora-gallery"
        ));
        assert!(tar_listing_contains(entries, "liora-gallery/README.md"));
        assert!(!tar_listing_contains(entries, "liora-gallery/missing"));
    }

    #[test]
    fn generate_rpm_args_use_metadata_overwrite_branch() {
        let args = generate_rpm_args(
            Path::new("/repo/liora"),
            KnownApp::Gallery,
            Path::new("/repo/liora/target/liora-packager/GenerateRpm.gallery.toml"),
            Path::new("/repo/liora/target/packages/liora-gallery/linux"),
        );
        assert!(args.contains(&"generate-rpm".into()));
        assert!(args.contains(&"--metadata-overwrite".into()));
        assert!(args.contains(
            &"/repo/liora/target/liora-packager/GenerateRpm.gallery.toml#package.metadata.generate-rpm"
                .into()
        ));
    }

    #[test]
    fn install_smoke_plan_contains_install_and_uninstall_steps() {
        let app = KnownApp::Gallery.metadata();
        let plan = install_smoke_plan(
            &app,
            Platform::Linux,
            PackageFormat::Deb,
            Path::new("target/packages/liora-gallery/linux/liora-gallery.deb"),
        );

        assert!(plan.contains("sudo dpkg -i"));
        assert!(plan.contains("sudo apt-get remove"));
        assert!(plan.contains("liora-gallery"));
    }

    #[test]
    fn install_smoke_command_parse_defaults_to_plan_only() {
        let command = PackageCommand::parse(vec![
            "install-smoke".into(),
            "--all-apps".into(),
            "--format".into(),
            "tar.gz".into(),
        ])
        .unwrap();

        assert_eq!(command.action, PackageAction::InstallSmoke);
        assert_eq!(command.format, PackageFormat::TarGz);
        assert!(!command.dry_run);
        assert!(!command.execute_install);
        assert_eq!(command.apps.len(), liora_packager::known_apps().len());
    }

    #[test]
    fn install_smoke_execute_flag_is_explicit() {
        let command = PackageCommand::parse(vec![
            "install-smoke".into(),
            "--format".into(),
            "tar.gz".into(),
            "--execute-install".into(),
        ])
        .unwrap();

        assert!(command.execute_install);
    }

    #[test]
    fn install_smoke_dry_run_is_plan_only() {
        let command = PackageCommand::parse(vec![
            "install-smoke".into(),
            "--all-apps".into(),
            "--format".into(),
            "platform-defaults".into(),
            "--dry-run".into(),
        ])
        .unwrap();

        assert_eq!(command.action, PackageAction::InstallSmoke);
        assert!(command.dry_run);
        assert!(!command.execute_install);
    }

    #[test]
    fn expected_tar_gz_path_matches_portable_backend_name() {
        let path = expected_artifact_path(
            Path::new("target/packages/liora-gallery/linux"),
            "liora-gallery",
            Platform::Linux,
            PackageFormat::TarGz,
            FontVariant::WithoutFonts,
        );

        assert!(path.to_string_lossy().contains("liora-gallery-"));
        assert!(path.to_string_lossy().ends_with(".tar.gz"));
    }

    #[test]
    fn release_readiness_action_parses() {
        let command = PackageCommand::parse(vec!["release-readiness".into()]).unwrap();
        assert_eq!(command.action, PackageAction::ReleaseReadiness);
    }

    #[test]
    fn signing_env_missing_is_platform_specific() {
        assert!(signing_env_missing(Platform::Linux).is_empty());
        let macos_missing = signing_env_missing(Platform::Macos);
        assert!(macos_missing.contains(&"LIORA_MACOS_CODESIGN_IDENTITY"));
        let windows_missing = signing_env_missing(Platform::Windows);
        assert!(windows_missing.contains(&"LIORA_WINDOWS_SIGNTOOL_CERT_PATH"));
    }

    #[test]
    fn release_readiness_markdown_escapes_table_cells() {
        let mut report = ReleaseReadinessReport::default();
        report.warn("a|b", "line 1\nline 2");
        let text = report.to_markdown();
        assert!(text.contains("a\\|b"));
        assert!(text.contains("line 1<br>line 2"));
    }
}
